username: 
password: 

positions:
- Software Engineer sponsorship
- PHP sponsorship
- React sponsorship
- Shopify sponsorship

keywords:
- PHP
- Laravel
- React
- Shopify
- Python
- Javascript


locations:
- Remote
- Canada
- Germany
- Australia

